apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-shared
  namespace: llm-explorer
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 4cf2daa1-6955-4047-8809-faa6877a8c68
